# -*- coding: utf-8 -*-
"""tarea 3.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmEDh61y3sSjbxQe5AhbxMG-gbGe61_T
"""

import secrets
import random
import numpy as np

dat = [] #conjunto de valores que entrega err
gente = [] #convunto con todos los valores individuales de v,m,a
#se explicaran mas adelante su funcion de estas variables

#esta funcion se encarga de agragar los elementos nesesarios a gente
for i in range(100):
  if i < 50: #agrega 50 v de verdad
    gente.append("v")
  if i >= 50 and i < 80:#agrega 30 m de mentira
    gente.append("m")
  if i >= 80:#agrega 2 a de abtinencia
     gente.append("a")

#definimos mont el cual es la funcion que se encargara de tomar una muestra de gente y ver como esta distribuido
def mont():
  must = secrets.SystemRandom().sample(gente, 30) #se encarga de tomar la muestra de manera aleatoria
  v = 0 #numero total de v que aparescan en la muestra
  m = 0 #numero total de m que aparescan en la muestra
  a = 0 #numero total de a que aparescan en la muestra
  for i in range(30):#se encarga de revisar cada elemento del conjunto must y contavilisar la aparicion de v,m,a con un maximo de 10 si v,m,a son mayores a 10 en la muestra solo se contavilisara hasta 10
    if must[i] == "v" and v <= 10:
      v = v + 1
    else:
      if must[i] == "m" and m <= 10:
        m = m + 1
      else:
        if must[i] == "a" and a <= 10:
          a = a + 1
  #devido a la peculiar forma de contavilisar v,m,a h tiene un valor maximo de 30 que solo se cumple si a = m = v = 10 que queremos revisar que aparesca
  h = v + m + a
  return h

#esta funcion se encarga de repetir mount una cantidad N veces
def err():
  s = 0 #numero de veses que el evento especificado aparece
  N = 100000 #numero de veses que se repite mout en err
  for i in range(N):
    h = mont()
    if h == 30:#cada ves que h == 30 y por ende lo que investigamos haya susedido s ahumenta su valor en 1
      s += 1
  pro = s/N #por la definicion mas simple de probabilidad tomamos s y lo partimos N para calcular la probabilidad de que s suseda
  return pro
#este ciclo for se encarga de crear una lista con los distintos valores tomado de cada iteracion de err en este caso 10
for j in range(10):
  pro = err()
  dat.append(pro)#lista con todos los valores dintintos de pro

an = dat[0] #primer elemento de dat se ocuparta como referencia
error = [] #se guardaran cada diferencia de dat an - dat[i]

for i in range(1,10):
   error.append(np.abs(dat[i] - an))# se llena dar con la diferencia de dat[i] - an que se aproxima el error del sistema
print(error)

errmedi = sum(error)/len(error)#al tomar una media del error ago una proximacion mas fiable del error del sistema
print(errmedi, "error estimado") #el error puede variar un poco pero